services:
  - type: web
    name: kika-backend
    env: python
    runtime: docker
    plan: free
    region: frankfurt
    buildCommand: docker build -t kika-backend .
    startCommand: ./entrypoint.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PORT
        value: 80
